## 1. Set working directory and load in the data. Also view snippets of the data
setwd("C:\\Users\\Hp\\Documents\\promise aguda") 
getwd()
## 2. Install and load required packages 
if(!require(seminr)) install.packages("seminr", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(semPlot)) install.packages("semPlot", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(dplyr)) install.packages("dplyr", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(tibble)) install.packages("tibble", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(readr)) install.packages("readr", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(ggplot2)) install.packages("ggplot2", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(lavaan)) install.packages("lavaan", repos="https://cloud.r-project.org") # Skip if already installed
# if(!require(readxl)) install.packages("readxl", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(openxlsx)) install.packages("openxlsx", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(DiagrammeR)) install.packages("Diagrammer", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(rsvg)) install.packages("rsvg", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(csem)) install.packages("csem", repos="https://cloud.r-project.org") # Skip if already installed
if(!require(car)) install.packages("car", repos="https://cloud.r-project.org") # Skip if already installed


library(tibble)
# library(readxl) # Import an Excel file
library(readr)
library(ggplot2)
library(seminr)
library(cSEM)
library(semPlot)
library(dplyr)
library(DiagrammeR)
library(openxlsx)
library(rsvg) # To allow saving of plots
library(car)

set.seed(123)


### Check the corresponding R valid colors for the beLow
# grDevices::colors()



## Set the theme to use. Alternative is to use formatting options inside the plots
thm <- seminr_theme_create(
  plot.rounding = 3,
  plot.adj = FALSE,
  sm.node.fill = "royalblue", 
  mm.node.fill = "yellow",construct.compositeA.arrow = "backward",
  plot.fontname = "Arial",sm.edge.minlen = 3,plot.splines = FALSE,
  sm.edge.width_multiplier = 1, mm.edge.width_multiplier =1,
  mm.edge.boot.show_p_value = TRUE, sm.edge.boot.show_p_value = TRUE,
  construct.compositeA.shape = "circle", mm.node.color= "yellow",
  sm.node.color = "royalblue",manifest.reflective.shape = "box",
  mm.edge.label.fontcolor= "black",sm.edge.width_offset = 0.1,
  sm.edge.label.fontcolor = "black",
  sm.edge.positive.color = "black",
  mm.edge.positive.color = "black",
  plot.bgcolor = "white")

## Use the theme in the R Studio session
seminr_theme_set(thm) # Use autocomplete to discover all possible theme options!



################################################# Objective One #################################################################
# dt <- read_excel("Promise Aguda New Data - PL-SEM.xlsx") # Attempt to use an Excel file

dt <- read.csv("Promise Aguda New Data - PL-SEM.csv", header = TRUE, sep = ",")
head(dt)
tail(dt)
View(dt)
glimpse(dt)
class(dt)
colnames(dt)[1:34] # Check column names

## 3. Define measurement model

mm <- constructs(
  composite("MAT.DAS", multi_items("MAT.DAS", 1:5), weights = mode_A),
  composite("MAT.A", multi_items("MAT.A", 1:5), weights = mode_A), 
  composite("MAT.FAR", multi_items("MAT.FAR", 1:5), weights = mode_A),  
  # composite("MAT.DAS", multi_items("MAT.DAS", 1:5), weights = mode_B),    # Use if the choice is formative model 
  # composite("MAT.A", multi_items("MAT.A", 1:5), weights = mode_B),  # Use if the choice is formative model 
  # composite("MAT.FAR", multi_items("MAT.FAR", 1:5), weights = mode_B),   # Use if the choice is formative model 
  composite("OP",  multi_items("OP", 1:3), weights = mode_A) 
  
)

## 4. Structural model
#sm <- relationships(
#  paths(from = C("MAT.DAS","MAT.A","MAT.FAR"), to = "OP"))

## Create the structural model
sm <- relationships(
  paths(from = "MAT.DAS", to = "OP"),
  paths(from = "MAT.A", to = "OP"),
  paths(from = "MAT.FAR", to = "OP")
) 



## 5. Estimate model
pls_model <- estimate_pls(data = dt, measurement_model = mm, structural_model = sm, inner_weights = path_weighting,
                          missing = mean_replacement,
                          missing_value = "-99")

summary(pls_model)

### 6. Summarizing the model
# Once the model has been estimated, a summarized report of the results can be generated by using the summary() function.
summary_pls_model <- summary(pls_model)

#### calling summary_pls_model$total_effects, we inspect the model's total effects
summary_pls_model$total_effects

#### calling summary_pls_model$total_indirect_effects, we inspect the model's total indirect effects
summary_pls_model$total_indirect_effects

#### calling summary_pls_model$paths, we inspect the model’s path coefficients and the (adjusted) R2 values 
summary_pls_model$paths

#### calling summary_pls_model$reliability, we inspect the construct reliability metrics
summary_pls_model$reliability


#### we can plot the reliability
plot(summary_pls_model$reliability)


#### calling summary_pls_model$validity, we inspect the construct validity metrics # Check this out first to see contents

summary_pls_model$validity 

#### calling summary_pls_model$validity$fl_criteria, we obtain Discriminant validity, specifically, Fornell-Larcker criterion (Fornell & Larcker, 1981)
summary_pls_model$validity$fl_criteria

#### Calling summary_pls_model$validity$htmt, we inspect heterotrait-monotrait ratio (HTMT)
summary_pls_model$validity$htmt


### Calling summary_pls_model$validity$vif_item, we inspect the VIF for collinearity
summary_pls_model$validity$vif_items



# Normal (objective 1) collinearity fix - Make it be in data frame
## A mediator might not have item-level VIFs. So, NA is reported
# Convert VIF list into a tidy data frame, including empty constructs

collinearity_df <- do.call(rbind, lapply(names(summary_pls_model$validity$vif_items), function(construct) {
  vif_vals <- summary_pls_model$validity$vif_items[[construct]]
  
  if (length(vif_vals) == 0) {
    # If construct has no VIF items, add a placeholder
    data.frame(
      Construct = construct,
      Item      = NA,
      VIF       = NA
    )
  } else {
    data.frame(
      Construct = construct,
      Item      = names(vif_vals),
      VIF       = unname(vif_vals)
    )
  }
}))







#### We can access summary statistics of the model’s items
items_statistics_summary_pls_model<- summary_pls_model$descriptives$statistics$items
items_statistics_summary_pls_model


#### To get the construct statistics.
constructs_statistics_summary_pls_model <-  summary_pls_model$descriptives$statistics$constructs
constructs_statistics_summary_pls_model


##. Construct scores (latent variable scores)

construct_scores <- summary_pls_model$composite_scores 
construct_scores

### Alternative to the above
#construct_scores <- pls_model$construct_scores
#construct_scores

##. Outer loadings (indicator reliability)
pls_model$outer_loadings

## Or
outer_loadings_pls_model <- summary_pls_model$loadings
print(outer_loadings_pls_model)


##. weights
pls_model$outer_weights

# Or
outer_weights_pls_model <- summary_pls_model$weights
print(outer_weights_pls_model)


## Cross Loading
summary_pls_model$validity$cross_loadings

# To get the effect size
fsquare_pls_model  <- summary_pls_model$fSquare
fsquare_pls_model




### Get model fit using the cSEM package

csem_model <- "

# measurement model
MAT.DAS =~ MAT.DAS1 + MAT.DAS2 + MAT.DAS3
MAT.A =~ MAT.A1 + MAT.A2 + MAT.A3
MAT.FAR =~ MAT.FAR1 + MAT.FAR2 + MAT.FAR3
OP =~ OP1 + OP2 + OP3

# Structural model 

OP ~ MAT.DAS + MAT.A + MAT.FAR
"
mf <- 
  csem(.data = dt, .model = csem_model)

mf_results <- assess <- assess(.object = mf, .quality_criterion =
                                 c("srmr", "dg","dl","chi_square"))



mf_results

class(mf_results)



# Saving the PL-SEM results to file

## Summarize the PLS-SEM model outputs and take them to a single Excel file


####################### FORMATTED Version ##########################################################################


### Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)


wb <- createWorkbook()
addWorksheet(wb, "total_effects"); writeData(wb, "total_effects", summary_pls_model$total_effects, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "total_indirect_effects"); writeData(wb, "total_indirect_effects", summary_pls_model$total_indirect_effects, headerStyle = 										header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "Paths");        writeData(wb, "Paths", summary_pls_model$paths,, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "Loadings");     writeData(wb, "Loadings", summary_pls_model$loadings,, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "cross_loadings");     writeData(wb, "cross_loadings", summary_pls_model$validity$cross_loadings, headerStyle = 	header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "Weights");      writeData(wb, "Weights", summary_pls_model$weights, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "Reliability");  writeData(wb, "Reliability", summary_pls_model$reliability, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "HTMT");         writeData(wb, "HTMT", summary_pls_model$validity$htmt, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "fSquare");      writeData(wb, "fSquare", summary_pls_model$fSquare, headerStyle = header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "collinearity_df");  writeData(wb, "collinearity_df", collinearity_df, headerStyle = header_style, borders = 										"all", rowNames = TRUE)
addWorksheet(wb, "fornell_larcker"); writeData(wb, "fornell_larcker", summary_pls_model$validity$fl_criteria, headerStyle = header_style, 										borders = "all", rowNames = TRUE)
addWorksheet(wb, "items_statistics"); writeData(wb, "items_statistics", summary_pls_model$descriptives$statistics$items, headerStyle = 									header_style, borders = "all", rowNames = TRUE)
addWorksheet(wb, "construct_scores"); writeData(wb, "construct_scores", summary_pls_model$composite_scores, headerStyle = 									header_style, borders = "all", rowNames = TRUE)

saveWorkbook(wb, "Objective 1-PLS-SEM - Promise Aguda.xlsx", overwrite = TRUE)


# Bootstrapping the results

boot_model <- bootstrap_model(seminr_model = pls_model,
                              nboot = 1000,
                              cores = NULL,
                              seed = 123)

sum_boot_model <- summary(boot_model, , alpha = 0.05)


#### Obtain bootstrapping results on model estimates such as the path coefficients with sum_boot_model$bootstrapped_paths.

######## Get the P-value and save the bootstrapping result to csv #################################

sum_boot_paths <- sum_boot_model$bootstrapped_paths
sum_boot_paths


### Check the class of  sum_boot_paths

class(sum_boot_paths)

# Check the rowNames which is expected to be the paths values with no recognized column header

rownames(sum_boot_paths)



# Convert bootstrap results to data.frame 
sum_boot_paths <- as.data.frame(sum_boot_paths)
sum_boot_paths # Print to see the content


# Compute p-values (using "T Stat." column with dot)
sum_boot_paths$p_value <- round(2 * (1 - pnorm(abs(sum_boot_paths[,"T Stat."]))),4)

### Get the column headers
colnames(sum_boot_paths)
head(sum_boot_paths)

# Add significance levels
sum_boot_paths$Significance <- cut(
  sum_boot_paths$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)


# Create a clean table with selected columns
clean_results_paths <- sum_boot_paths[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                          "2.5% CI","97.5% CI", "p_value" ,      
                                          "Significance" )]

# Rename columns for clarity
colnames(clean_results_paths) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                    "2.5% CI","97.5% CI", "P-value" ,      
                                    "Significance" )

# Check to see the difference
sum_boot_paths
clean_results_paths

# Export to CSV (saves in working directory)
write.csv(
  clean_results_paths,
  file = "Objective 1- paths_bootstrap_results- Promise Aguda.csv",
  row.names = TRUE
)

# Confirm location
cat("✅ Clean results with CIs saved as 'Objective 1- paths_bootstrap_results- Promise Aguda.csv' in your working directory\n")



#### Bootstrapping of outer loadings 

####### Get the P-value and save the bootstrapping result to csv #################################


sum_boot_loadings  <- sum_boot_model$bootstrapped_loadings

### Check the class of  sum_boot_loadings

class(sum_boot_loadings)

# Check the rowNames
rownames(sum_boot_loadings)

# Convert bootstrap results to data.frame 
sum_boot_loadings <- as.data.frame(sum_boot_loadings)
sum_boot_loadings  # Print to see the content


# Compute p-values (using "T Stat." column with dot)
sum_boot_loadings$p_value <- round(2 * (1 - pnorm(abs(sum_boot_loadings[,"T Stat."]))),4)

### Get the column headers
colnames(sum_boot_loadings)
head(sum_boot_loadings)

# Add significance levels
sum_boot_loadings$Significance <- cut(
  sum_boot_loadings$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
loadings_clean_results <- sum_boot_loadings[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",  
                                                "2.5% CI","97.5% CI", "p_value" ,      
                                                "Significance" )]

# Rename columns for clarity
colnames(loadings_clean_results) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                       "2.5% CI","97.5% CI", "P-value" ,      
                                       "Significance" ) 



# Check to see the difference
sum_boot_loadings
loadings_clean_results

# Export to CSV (saves in working directory)
write.csv(
  loadings_clean_results,
  file = "Objective 1- loadings_boostrap_result- Promise Aguda.csv",
  row.names = TRUE
)

# Confirm location
cat("✅ Clean results of loadings with CIs saved as 'Objective 1- loadings_boostrap_result- Promise Aguda.csv' in your working directory\n")




### Bootstrapping the model fit result

boot_mf <-
  
  csem(.data = dt, .model = csem_model,
       .resample_method = "bootstrap", .R = 1000)

boot_mf_results <- assess(boot_mf)

boot_mf_results 

class(boot_mf_results)

# Saving the bootstrapping results to file


####################### FORMATTED VERSION ##########################################################################


# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file

# Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)

wb <- createWorkbook()

# --- Bootstrap results ---

addWorksheet(wb, "sum_boot_paths"); writeData(wb, "sum_boot_paths",  clean_results_paths, headerStyle = header_style, borders = "all",rowNames = TRUE) 
# or sum_boot_paths for clean_results_paths

addWorksheet(wb, "sum_boot_loadings"); writeData(wb, "sum_boot_loadings",  loadings_clean_results, headerStyle = header_style, borders = "all",rowNames = TRUE) # sum_boot_loadings for loadings_clean_result

saveWorkbook(wb, "Objective 1-PL-SEM - Promise Aguda - Bootstrap.xlsx", overwrite = TRUE)


# Create the Visualization
plot(pls_model,
     what = "paths",
     engine = "Diagrammer",
     title = " ",
     layout = "tree")

# To save the plot
# save_plot("Objective 1-PLS-SEM - Promise Aguda.png") # Export is better

# Save high-quality PNG
save_plot(filename = "Objective 1-PLS-SEM - Promise Aguda.png",
          width = 400, height = 200) # , dpi = 600. Export is better

dev.off()




################################################# Objective Two - Moderation Analysis ###############################################################


## Create the measurement model

mm_mod <- constructs(
  composite("MAT", multi_items("MAT", 1:3), weights = mode_A),
  composite("FL",  multi_items("FL", 1:8), weights = mode_A),
  composite("OP",  multi_items("OP", 1:3), weights = mode_A),
  #composite("MAT",  multi_items("MAT", 1:4), weights = mode_B),  # Formative model
  interaction_term(iv = "MAT", moderator = "FL", method = product_indicator)) # You can also use methods like product_indicator, two_stage or orthogonal


## Create the structural model
sm_mod <- relationships(
  paths(from = c("MAT", "FL", "MAT*FL"), to = "OP") # Interaction of independent and moderating variables
)

## Create the structural model - Method 2
#sm_mod <- relationships(
#paths(from = "MAT", to = "OP"),
#paths(from = "FL", to = "OP"),
#paths(from = "MAT*FL", to = "OP") # Interaction of independent and moderating variables
#)


### Check the constructs
mm_mod


# Next, we estimate the model with estimate_pls(), store it to pl_sm_mod and summarize it to sum_pls_mod. Further, we also apply bootstrapping and summarize the bootstrapped model with an alpha level of 5% 

## Estimate the new model with moderator
pl_sm_mod <- estimate_pls(
  data = dt,
  measurement_model = mm_mod,
  structural_model = sm_mod,
  missing = mean_replacement,
  missing_value = "-99"
)


summary(pl_sm_mod)


# Once the model has been estimated, a summarized report of the results can be generated by using the summary() function.
## Extract the summary

sum_pls_mod <- summary(pl_sm_mod)


#### calling sum_pls_mod$total_effects, we inspect the model's total effects
sum_pls_mod$total_effects

#### calling sum_pls_mod$total_indirect_effects, we inspect the model's total indirect effects

sum_pls_mod$total_indirect_effects


#### calling sum_pls_mod$paths, we inspect the model’s path coefficients and the (adjusted) R2 values 
sum_pls_mod$paths


#### calling sum_pls_mod$reliability, we inspect the construct reliability metrics
sum_pls_mod$reliability


#### we can plot the reliability
plot(sum_pls_mod$reliability)


#### calling sum_pls_model$validity, we inspect the construct validity metrics # Check this out first to see contents

sum_pls_mod$validity 


#### calling sum_pls_mod$validity$fl_criteria, we obtain Discriminant validty, specifically, Fornell-Larcker criterion (Fornell & Larcker, 1981)
sum_pls_mod$validity$fl_criteria

#### Calling sum_pls_mod$validity$htmt, we inspect heterotrait-monotrait ratio (HTMT)
sum_pls_mod$validity$htmt

### Calling sum_pls_model$vif_antecedents, we inspect the VIF for collinearity

sum_pls_mod$validity$vif_items

# Moderation collinearity fix
## a mediator might not have item-level VIFs. So, NA is reported
# Convert VIF list into a tidy data frame, including empty constructs
collinearity_mod_df <- do.call(rbind, lapply(names(sum_pls_mod$validity$vif_items), function(construct) {
  vif_vals <- sum_pls_mod$validity$vif_items[[construct]] 
  if (length(vif_vals) == 0) {
    # If construct has no VIF items, add a placeholder
    data.frame(
      Construct = construct,
      Item      = NA,
      VIF       = NA
    )
  } else {
    data.frame(
      Construct = construct,
      Item      = names(vif_vals),
      VIF       = unname(vif_vals)
    )
  }
}))





#### We can access summary statistics such as mean, standard deviation and number of missing values for the model’s items
sum_pls_mod$descriptives$statistics$items

#### To get the construct statistics
sum_pls_mod$descriptives$statistics$constructs

## Construct scores (latent variable scores)

construct_scores_pls_mod <- sum_pls_mod$composite_scores 

### Alternative to the above
#construct_scores_pls_mod <- pl_sm_mod$construct_scores

## Outer loadings (indicator reliability)
sum_pls_mod$loadings

## Or
outer_loadings_pl_sm_mod <- pl_sm_mod$outer_loadings
print(outer_loadings_pl_sm_mod)


## weights
pl_sm_mod$outer_weights

# Or
outer_weights_pl_sm_mod <- sum_pls_mod$weights
print(outer_weights_pl_sm_mod)

## Cross Loading
sum_pls_mod$validity$cross_loadings


# To get the effect size
fsquare_pls_mod  <- sum_pls_mod$fSquare




### Get model fit using the cSEM package

csem_model_mod <- "

# measurement model
MAT =~ MAT1 + MAT2 + MAT3
FL =~ FL1 + FL2 + FL3 + FL4 + FL5 + FL6 + FL7 + FL8
OP =~ OP1 + OP2 + OP3

# Structural model 

OP ~ MAT + FL + MAT.FL

# Define the interaction (two-stage approach)
MAT.FL <- MAT*FL

"
mf <- 
  csem(.data = dt, .model = csem_model)

mf_results_mod <- assess <- assess(.object = mf, .quality_criterion =
                                     c("srmr", "dg","dl","chi_square"))


mf_results_mod


# Saving the PL-SEM results to file



####################### FORMATTED VERSION ##########################################################################


## Summarize the PLS-SEM model outputs and take them to a single Excel file

### Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)


wb <- createWorkbook()
addWorksheet(wb, "total_effects_mod"); writeData(wb, "total_effects_mod", sum_pls_mod$total_effects, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "total_indirect_effects_mod"); writeData(wb, "total_indirect_effects_mod", sum_pls_mod$total_indirect_effects, headerStyle = 										header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Paths_mod");        writeData(wb, "Paths_mod", sum_pls_mod$paths,, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Loadings_mod");     writeData(wb, "Loadings_mod", sum_pls_mod$loadings,headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "cross_loadings_mod");     writeData(wb, "cross_loadings_mod", sum_pls_mod$validity$cross_loadings, headerStyle 																	= 															header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "Weights_mod");      writeData(wb, "Weights_mod", sum_pls_mod$weights, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Reliability_mod");  writeData(wb, "Reliability_mod", sum_pls_mod$reliability, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "HTMT_mod");         writeData(wb, "HTMT_mod",sum_pls_mod$validity$htmt, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "fSquare_mod");      writeData(wb, "fSquare_mod", sum_pls_mod$fSquare, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "collinearity_mod_df");  writeData(wb, "collinearity_mod_df", collinearity_mod_df, headerStyle = header_style, borders = 										"all",rowNames = TRUE)
addWorksheet(wb, "fornell_larcker_mod"); writeData(wb, "fornell_larcker_mod", sum_pls_mod$validity$fl_criteria, headerStyle = header_style, 										borders = "all",rowNames = TRUE)
addWorksheet(wb, "items_statistics_mod"); writeData(wb, "items_statistics_mod", sum_pls_mod$descriptives$statistics$items, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "construct_scores_mod"); writeData(wb, "construct_scores_mod", sum_pls_mod$composite_scores, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

saveWorkbook(wb, "Moderation-PLS-SEM - Promise Aguda- Objective 2.xlsx", overwrite = TRUE)



### Bootstrapping the results
boot_pls_mod <- bootstrap_model(seminr_model = pl_sm_mod,
                                nboot = 1000,
                                cores = NULL,
                                seed = 123)

## Summarize the results of the bootstrap
sum_boot_pls_mod <- summary(boot_pls_mod, alpha = 0.05)

#### Obtain results on model estimates such as the path coefficients with sum_boot_pls_mod$bootstrapped_paths.
######## Get the P-value and save the bootstrapping result to csv #################################

sum_boot_paths_mod <- sum_boot_pls_mod$bootstrapped_paths

### Check the class of  sum_boot_paths

class(sum_boot_paths_mod)

# Check the rownames 

rownames(sum_boot_paths_mod)

# Convert bootstrap results to data.frame 
sum_boot_paths_mod <- as.data.frame(sum_boot_paths_mod)
sum_boot_paths_mod # Print to see the content


# Compute p-values (using "T Stat." column with dot)
sum_boot_paths_mod$p_value <- round(2 * (1 - pnorm(abs(sum_boot_paths_mod[,"T Stat."]))),4)

colnames(sum_boot_paths_mod)
head(sum_boot_paths_mod)

# Add significance levels
sum_boot_paths_mod$Significance <- cut(
  sum_boot_paths_mod$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_paths_mod <- sum_boot_paths_mod[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                  "2.5% CI","97.5% CI", "p_value" ,      
                                                  "Significance" )]

# Rename columns for clarity
colnames(clean_results_paths_mod) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                        "2.5% CI","97.5% CI", "P-value" ,      
                                        "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_paths_mod,
  file = "path_bootstrap_results_mod- Promise Aguda- Objective 2.csv",
  row.names = TRUE)


# Confirm location
cat("✅ Clean results with CIs saved as 'path_bootstrap_results_mod- Promise Aguda- Objective 2.csv' in your working directory\n")





#### Bootstrapping of outer loadings 
####### Get the P-value and save the bootstrapping result to csv #################################

sum_boot_loadings_mod  <- sum_boot_pls_mod$bootstrapped_loadings

### Check the class of  sum_boot_paths

class(sum_boot_loadings_mod)

# Check the rownames 

rownames(sum_boot_loadings_mod)


# Convert bootstrap results to data.frame 
sum_boot_loadings_mod <- as.data.frame(sum_boot_loadings_mod)
sum_boot_loadings_mod  # Print to see the content



# Compute p-values (using "T Stat." column with dot)
sum_boot_loadings_mod$p_value <- round(2 * (1 - pnorm(abs(sum_boot_loadings_mod[,"T Stat."]))),4)

### Get the column headers
colnames(sum_boot_loadings_mod)
head(sum_boot_loadings_mod)

# Add significance levels
sum_boot_loadings_mod$Significance <- cut(
  sum_boot_loadings_mod$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_loadings_mod <- sum_boot_loadings_mod[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                        "2.5% CI","97.5% CI", "p_value" ,      
                                                        "Significance" )]

# Rename columns for clarity
colnames(clean_results_loadings_mod) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                           "2.5% CI","97.5% CI", "P-value" ,      
                                           "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_loadings_mod,
  file = "loadings_boostrap_mod- Promise Aguda- Objective 2.csv",
  row.names = TRUE
)



# Confirm location
cat("✅ Clean results of loadings with CIs saved as 'outer_loadings_boostrap_mod- Promise Aguda- Objective 2.csv' in your working directory\n")



### Bootstrapping the model fit result

boot_mf_mod <-
  
  csem(.data = dt, .model = csem_model_mod,
       .resample_method = "bootstrap", .R = 1000)

boot_mf_results_mod <- assess(boot_mf_mod)


boot_mf_results_mod

# Saving the bootstrapping results to file


####################### FORMATTED VERSION ##########################################################################


# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file

# Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)

wb <- createWorkbook()

# --- Bootstrap results ---

addWorksheet(wb, "sum_boot_paths_mod"); writeData(wb, "sum_boot_paths_mod", sum_boot_paths_mod, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "sum_boot_loadings_mod"); writeData(wb, "sum_boot_loadings_mod", clean_results_loadings_mod, headerStyle = header_style, borders = "all",rowNames = TRUE)

saveWorkbook(wb, "Promise Aguda PLS_SEM_with_BootstrapMod- Objective 2.xlsx ", overwrite = TRUE)

message("✅ Export complete: Bootstrap results written to Promise Aguda PLS_SEM_with_BootstrapMod- Objective 2.xlsx")


# To better comprehend the results of the moderator analysis,
# we use the slope_analysis() function to visualize the two-way interaction effect. 

slope_analysis(
  moderated_model = pl_sm_mod, 
  dv = "OP",
  moderator = "FL",
  iv = "MAT",
  leg_place = "bottomright")

# Create the Visualization

plot(pl_sm_mod,
     what = "paths",
     engine = "DiagrammeR",
     title = ,
     node_labels = TRUE,
     node_color = "lightgreen",
     node_shape = "ellipse",
     fontname = "Arial",
     fontsize = 12,
     edge_labels = TRUE,
     edge_label_color = "black",
     edge_color = "darkblue",
     edge_width = 2,
     layout = "tree")
dev.off()

# Saving the plot
save_plot("Promise Aguda Objective 2 - Moderation image.png")




################################################# Objective Three - Moderation Analysis ###############################################################

## Create the measurement model

mm_mod <- constructs(
  composite("MAT", multi_items("MAT", 1:3), weights = mode_A),
  composite("ITR",  multi_items("ITR", 1:5), weights = mode_A),
  composite("OP",  multi_items("OP", 1:3), weights = mode_A),
  #composite("ITR",  multi_items("ITR", 1:5), weights = mode_B),   # Formative model
  #composite("MAT",  multi_items("MAT", 1:4), weights = mode_B),  # Formative model
  interaction_term(iv = "MAT", moderator = "ITR", method = product_indicator)) # You can also use methods like product_indicator, two_stage or orthogonal


## Create the structural model
sm_mod <- relationships(
  paths(from = c("MAT", "ITR", "MAT*ITR"), to = "OP") # Interaction of independent and moderating variables
)

## Create the structural model - Method 2
#sm_mod <- relationships(
#paths(from = "MAT", to = "OP"),
#paths(from = "ITR", to = "OP"),
#paths(from = "MAT*ITR", to = "OP") # Interaction of independent and moderating variables
#)


### Check the constructs
mm_mod


# Next, we estimate the model with estimate_pls(), store it to pl_sm_mod and summarize it to sum_pls_mod. Further, we also apply bootstrapping and summarize the bootstrapped model with an alpha level of 5% 

## Estimate the new model with moderator
pl_sm_mod <- estimate_pls(
  data = dt,
  measurement_model = mm_mod,
  structural_model = sm_mod,
  missing = mean_replacement,
  missing_value = "-99"
)


summary(pl_sm_mod)


# Once the model has been estimated, a summarized report of the results can be generated by using the summary() function.
## Extract the summary

sum_pls_mod <- summary(pl_sm_mod)


#### calling sum_pls_mod$total_effects, we inspect the model's total effects
sum_pls_mod$total_effects

#### calling sum_pls_mod$total_indirect_effects, we inspect the model's total indirect effects

sum_pls_mod$total_indirect_effects


#### calling sum_pls_mod$paths, we inspect the model’s path coefficients and the (adjusted) R2 values 
sum_pls_mod$paths


#### calling sum_pls_mod$reliability, we inspect the construct reliability metrics
sum_pls_mod$reliability


#### we can plot the reliability
plot(sum_pls_mod$reliability)


#### calling sum_pls_model$validity, we inspect the construct validity metrics # Check this out first to see contents

sum_pls_mod$validity 


#### calling sum_pls_mod$validity$vif_criteria, we obtain Discriminant validty, specifically, Fornell-Larcker criterion (Fornell & Larcker, 1981)
sum_pls_mod$validity$fl_criteria

#### Calling sum_pls_mod$validity$htmt, we inspect heterotrait-monotrait ratio (HTMT)
sum_pls_mod$validity$htmt

### Calling sum_pls_model$vif_antecedents, we inspect the VIF for collinearity

sum_pls_mod$validity$vif_items

# Moderation collinearity fix
## a mediator might not have item-level VIFs. So, NA is reported
# Convert VIF list into a tidy data frame, including empty constructs
collinearity_mod_df <- do.call(rbind, lapply(names(sum_pls_mod$validity$vif_items), function(construct) {
  vif_vals <- sum_pls_mod$validity$vif_items[[construct]] 
  if (length(vif_vals) == 0) {
    # If construct has no VIF items, add a placeholder
    data.frame(
      Construct = construct,
      Item      = NA,
      VIF       = NA
    )
  } else {
    data.frame(
      Construct = construct,
      Item      = names(vif_vals),
      VIF       = unname(vif_vals)
    )
  }
}))




#### We can access summary statistics such as mean, standard deviation and number of missing values for the model’s items
sum_pls_mod$descriptives$statistics$items

#### To get the construct statistics
sum_pls_mod$descriptives$statistics$constructs

## Construct scores (latent variable scores)

construct_scores_pls_mod <- sum_pls_mod$composite_scores 

### Alternative to the above
#construct_scores_pls_mod <- pl_sm_mod$construct_scores

## Outer loadings (indicator reliability)
sum_pls_mod$loadings

## Or
outer_loadings_pl_sm_mod <- pl_sm_mod$outer_loadings
print(outer_loadings_pl_sm_mod)


## weights
pl_sm_mod$outer_weights

# Or
outer_weights_pl_sm_mod <- sum_pls_mod$weights
print(outer_weights_pl_sm_mod)

## Cross Loading
sum_pls_mod$validity$cross_loadings


# To get the effect size
fsquare_pls_mod  <- sum_pls_mod$fSquare




### Get model fit using the cSEM package

csem_model_mod <- "

# measurement model
MAT =~ MAT1 + MAT2 + MAT3
ITR =~ ITR1 + ITR2 + ITR3 + ITR4 + ITR5 + ITR6 + ITR7 + ITR8
OP =~ OP1 + OP2 + OP3

# Structural model 

OP ~ MAT + ITR + MAT.ITR

# Define the interaction (two-stage approach)
MAT.ITR <- MAT*ITR

"
mf <- 
  csem(.data = dt, .model = csem_model)

mf_results_mod <- assess <- assess(.object = mf, .quality_criterion =
                                     c("srmr", "dg","dl","chi_square"))


mf_results_mod


# Saving the PL-SEM results to file



####################### FORMATTED VERSION ##########################################################################


## Summarize the PLS-SEM model outputs and take them to a single Excel file

### Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)


wb <- createWorkbook()
addWorksheet(wb, "total_effects_mod"); writeData(wb, "total_effects_mod", sum_pls_mod$total_effects, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "total_indirect_effects_mod"); writeData(wb, "total_indirect_effects_mod", sum_pls_mod$total_indirect_effects, headerStyle = 										header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Paths_mod");        writeData(wb, "Paths_mod", sum_pls_mod$paths,, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Loadings_mod");     writeData(wb, "Loadings_mod", sum_pls_mod$loadings,headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "cross_loadings_mod");     writeData(wb, "cross_loadings_mod", sum_pls_mod$validity$cross_loadings, headerStyle 																	= 															header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "Weights_mod");      writeData(wb, "Weights_mod", sum_pls_mod$weights, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Reliability_mod");  writeData(wb, "Reliability_mod", sum_pls_mod$reliability, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "HTMT_mod");         writeData(wb, "HTMT_mod",sum_pls_mod$validity$htmt, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "fSquare_mod");      writeData(wb, "fSquare_mod", sum_pls_mod$fSquare, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "collinearity_mod_df");  writeData(wb, "collinearity_mod_df", collinearity_mod_df, headerStyle = header_style, borders = 										"all",rowNames = TRUE)
addWorksheet(wb, "fornell_larcker_mod"); writeData(wb, "fornell_larcker_mod", sum_pls_mod$validity$ITR_criteria, headerStyle = header_style, 										borders = "all",rowNames = TRUE)
addWorksheet(wb, "items_statistics_mod"); writeData(wb, "items_statistics_mod", sum_pls_mod$descriptives$statistics$items, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "construct_scores_mod"); writeData(wb, "construct_scores_mod", sum_pls_mod$composite_scores, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

saveWorkbook(wb, "Moderation-PLS-SEM - Promise Aguda- Objective 3.xlsx", overwrite = TRUE)



### Bootstrapping the results
boot_pls_mod <- bootstrap_model(seminr_model = pl_sm_mod,
                                nboot = 1000,
                                cores = NULL,
                                seed = 123)

## Summarize the results of the bootstrap
sum_boot_pls_mod <- summary(boot_pls_mod, alpha = 0.05)

#### Obtain results on model estimates such as the path coefficients with sum_boot_pls_mod$bootstrapped_paths.
######## Get the P-value and save the bootstrapping result to csv #################################

sum_boot_paths_mod <- sum_boot_pls_mod$bootstrapped_paths

### Check the class of  sum_boot_paths

class(sum_boot_paths_mod)

# Check the rownames 

rownames(sum_boot_paths_mod)

# Convert bootstrap results to data.frame 
sum_boot_paths_mod <- as.data.frame(sum_boot_paths_mod)
sum_boot_paths_mod # Print to see the content


# Compute p-values (using "T Stat." column with dot)
sum_boot_paths_mod$p_value <- round(2 * (1 - pnorm(abs(sum_boot_paths_mod[,"T Stat."]))),4)

colnames(sum_boot_paths_mod)
head(sum_boot_paths_mod)

# Add significance levels
sum_boot_paths_mod$Significance <- cut(
  sum_boot_paths_mod$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_paths_mod <- sum_boot_paths_mod[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                  "2.5% CI","97.5% CI", "p_value" ,      
                                                  "Significance" )]

# Rename columns for clarity
colnames(clean_results_paths_mod) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                        "2.5% CI","97.5% CI", "P-value" ,      
                                        "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_paths_mod,
  file = "path_bootstrap_results_mod- Promise Aguda- Objective 3.csv",
  row.names = TRUE)


# Confirm location
cat("✅ Clean results with CIs saved as 'path_bootstrap_results_mod- Promise Aguda- Objective 3.csv' in your working directory\n")





#### Bootstrapping of outer loadings 
####### Get the P-value and save the bootstrapping result to csv #################################

sum_boot_loadings_mod  <- sum_boot_pls_mod$bootstrapped_loadings

### Check the class of  sum_boot_paths

class(sum_boot_loadings_mod)

# Check the rownames 

rownames(sum_boot_loadings_mod)


# Convert bootstrap results to data.frame 
sum_boot_loadings_mod <- as.data.frame(sum_boot_loadings_mod)
sum_boot_loadings_mod  # Print to see the content



# Compute p-values (using "T Stat." column with dot)
sum_boot_loadings_mod$p_value <- round(2 * (1 - pnorm(abs(sum_boot_loadings_mod[,"T Stat."]))),4)

### Get the column headers
colnames(sum_boot_loadings_mod)
head(sum_boot_loadings_mod)

# Add significance levels
sum_boot_loadings_mod$Significance <- cut(
  sum_boot_loadings_mod$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_loadings_mod <- sum_boot_loadings_mod[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                        "2.5% CI","97.5% CI", "p_value" ,      
                                                        "Significance" )]

# Rename columns for clarity
colnames(clean_results_loadings_mod) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                           "2.5% CI","97.5% CI", "P-value" ,      
                                           "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_loadings_mod,
  file = "loadings_boostrap_mod- Promise Aguda- Objective 3.csv",
  row.names = TRUE
)



# Confirm location
cat("✅ Clean results of loadings with CIs saved as 'outer_loadings_boostrap_mod- Promise Aguda- Objective 3.csv' in your working directory\n")



### Bootstrapping the model fit result

boot_mf_mod <-
  
  csem(.data = dt, .model = csem_model_mod,
       .resample_method = "bootstrap", .R = 1000)

boot_mf_results_mod <- assess(boot_mf_mod)


boot_mf_results_mod

# Saving the bootstrapping results to file


####################### FORMATTED VERSION ##########################################################################


# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file

# Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)

wb <- createWorkbook()

# --- Bootstrap results ---

addWorksheet(wb, "sum_boot_paths_mod"); writeData(wb, "sum_boot_paths_mod", sum_boot_paths_mod, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "sum_boot_loadings_mod"); writeData(wb, "sum_boot_loadings_mod", clean_results_loadings_mod, headerStyle = header_style, borders = "all",rowNames = TRUE)

saveWorkbook(wb, "Promise Aguda PLS_SEM_with_BootstrapMod- Objective 3.xlsx ", overwrite = TRUE)

message("✅ Export complete: Bootstrap results written to Promise Aguda PLS_SEM_with_BootstrapMod- Objective 3.xlsx")


# To better comprehend the results of the moderator analysis,
# we use the slope_analysis() function to visualize the two-way interaction effect. 

slope_analysis(
  moderated_model = pl_sm_mod, 
  dv = "OP",
  moderator = "ITR",
  iv = "MAT",
  leg_place = "bottomright")

# Create the Visualization

plot(pl_sm_mod,
     what = "paths",
     engine = "DiagrammeR",
     title = ,
     node_labels = TRUE,
     node_color = "lightgreen",
     node_shape = "ellipse",
     fontname = "Arial",
     fontsize = 12,
     edge_labels = TRUE,
     edge_label_color = "black",
     edge_color = "darkblue",
     edge_width = 2,
     layout = "tree")
dev.off()

# Saving the plot
save_plot("Promise Aguda Objective 3 - Moderation image.png")








## Mediation Analysis not Part of the Objectives

###################### Mediation Analysis - Objective 2######################################################################################


## Create the measurement model

mm_med <- constructs(
  composite("MAT", multi_items("MAT", 1:3), weights = mode_A),
  composite("OP",  multi_items("OP", 1:3), weights = mode_A),
  composite("FL",  multi_items("FL", 1:8), weights = mode_A)
  #composite("MAT",  multi_items("MAT", 1:3), weights = mode_B),  # Formative model
  #composite("FL",  multi_items("FL", 1:8), weights = mode_B)    # Formative model
)  


## Create the structural model
sm_med <- relationships(
  paths(from = "MAT", to = "FL"),
  paths(from = "MAT", to = "OP"),
  paths(from = "FL", to = "OP")  # mediating effect
) 

## Create the structural model - Method 2
# Structural model with mediation
# sm_med <- relationships(
# paths(from = "MAT", to = c("FL", "OP")),  # MAT affects FL and OP
#  paths(from = "FL", to = "OP")             # FL mediates OP
#)


# Next, we estimate the model with estimate_pls(), store it to pl_sm_med and summarize it to sum_pls_med. Further, we also apply bootstrapping and summarize the bootstrapped model with an alpha level of 5% (summary(boot_corp_rep_med, alpha = 0.05))`

## Estimate the new model with mediator
pl_sm_med <- estimate_pls(
  data = dt,
  measurement_model = mm_med,
  structural_model = sm_med,
  # missing = mean_replacement,
  missing_value = "-99"
)

## Extract the summary
sum_pls_med <- summary(pl_sm_med)

### Inspect the total effects
sum_pls_med$total_effects

### Inspect the total indirect effects
sum_pls_med$total_indirect_effects


#### calling summary_pls_model$paths, we inspect the model's path coefficients and the (adjusted) R2 values 
sum_pls_med$paths

#### calling summary_pls_model$reliability, we inspect the construct reliability metrics
sum_pls_med$reliability


#### we can plot the reliability
plot(sum_pls_med$reliability)



#### calling summary_pls_model$validity, we inspect the construct validity metrics # Check this out first to see contents

sum_pls_med$validity


#### calling summary_pls_model$validity$fl_criteria, we obtain Discriminant validty, specifically, Fornell-Larcker criterion (Fornell &  Larcker, 1981)

sum_pls_med$validity$fl_criteria

#### Calling summary_pls_model$validity$htmt, we inspect heterotrait-monotrait ratio (HTMT)
sum_pls_med$validity$htmt


### Calling summary_pls_model$validity$vif_item, we inspect the VIF for collinearity

sum_pls_med$validity$vif_items



# Mediation collinearity fix - Make it be in data frame
## A mediator might not have item-level VIFs. So, NA is reported
# Convert VIF list into a tidy data frame, including empty constructs

collinearity_med_df <- do.call(rbind, lapply(names(sum_pls_med$validity$vif_items), function(construct) {
  vif_vals <- sum_pls_med$validity$vif_items[[construct]]
  
  if (length(vif_vals) == 0) {
    # If construct has no VIF items, add a placeholder
    data.frame(
      Construct = construct,
      Item      = NA,
      VIF       = NA
    )
  } else {
    data.frame(
      Construct = construct,
      Item      = names(vif_vals),
      VIF       = unname(vif_vals)
    )
  }
}))




#### We can access summary statistics such as mean, standard deviation and number of missing values for the model’s items

sum_pls_med$descriptives$statistics$items


##. Construct scores (latent variable scores)

construct_scores_med <- sum_pls_med$composite_scores 
construct_scores_med

# Alternative to the above
#construct_scores_med <- sum_pls_med$construct_scores
#construct_scores_med


##. Outer loadings (indicator reliability)
sum_pls_med$loadings

## Or
outer_loadings_pl_sm_med <- pl_sm_med$outer_loadings
print(outer_loadings_pl_sm_med)


##. weights
pl_sm_med$outer_weights

# Or
outer_weights_pl_sm_med <- sum_pls_med$weights
print(outer_weights_pl_sm_med)

# Compute cross-loadings manually
cross_loadings_pl_sm_med <- sum_pls_med$validity$cross_loadings


# To get the effect size
fsquare_pls_med  <- sum_pls_med$fSquare


### Calculate the sign of p1*p2*p3, i.e., sign of interaction

sign_med_FL <- sum_pls_med$paths["MAT","OP"]*sum_pls_med$paths["MAT","FL"]*sum_pls_med$paths["FL","OP"] # if positive, FL is a complementary partial mediator in # the relationship between MAT and OP
sign_med_FL
# if negative, FL is a competitive partial mediator in the relationship between  MAT and OP

### Try out - Check the components of the sign of interaction

sum_pls_med$paths["MAT","OP"]
sum_pls_med$paths["MAT","FL"]
sum_pls_med$paths["FL","OP"]



### Get model fit using the cSEM package

cSEM_model_med <- "

# measurement model
MAT =~ MAT1 + MAT2 + MAT3
OP =~ OP1 + OP2 + OP3
FL =~ FL1 + FL2 + FL3 + FL4 + FL5 + FL6 + FL7 + FL8

# Structural model 

OP ~ MAT + FL 

"
mf_med <- 
  cSEM(.data = dt, .model = cSEM_model_med)

mf_results_med <- assess <- assess(.object = mf_med, .quality_criterion =
                                     c("srmr", "dg","dl","chi_square"))

mf_results_med 

# Saving the PL-SEM results to file


####################### FORMATTED VERSION ##########################################################################


## Summarize the PLS-SEM model outputs and take them to a single Excel file

### Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)


wb <- createWorkbook()
addWorksheet(wb, "total_effects_med"); writeData(wb, "total_effects_med", sum_pls_med$total_effects, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "total_indirect_effects_med"); writeData(wb, "total_indirect_effects_med", sum_pls_med$total_indirect_effects, headerStyle = 										header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Paths_med");        writeData(wb, "Paths_med", sum_pls_med$paths, headerStyle = header_style, borders = "all",rowNames = 				TRUE)
addWorksheet(wb, "Loadings_med");     writeData(wb, "Loadings_med", sum_pls_med$loadings,, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "cross_loadings_med");     writeData(wb, "cross_loadings_med", sum_pls_med$validity$cross_loadings, headerStyle 																	= 															header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Weights_med");      writeData(wb, "Weights_med", sum_pls_med$weights, headerStyle = header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "Reliability_med");  writeData(wb, "Reliability_med", sum_pls_med$reliability, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "HTMT_med");         writeData(wb, "HTMT_med", sum_pls_med$validity$htmt, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "fSquare_med");      writeData(wb, "fSquare_med", sum_pls_med$fSquare, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "collinearity_med_df");  writeData(wb, "collinearity_med_df", collinearity_med_df, headerStyle = header_style, borders = 										"all",rowNames = TRUE)
addWorksheet(wb, "fornell_larcker_med"); writeData(wb, "fornell_larcker_med", sum_pls_med$validity$fl_criteria, headerStyle = header_style, 										borders = "all",rowNames = TRUE)

addWorksheet(wb, "items_statistics_med"); writeData(wb, "items_statistics_med", sum_pls_med$descriptives$statistics$items, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "construct_scores_med"); writeData(wb, "construct_scores_med",sum_pls_med$composite_scores, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "sign_med_FL"); writeData(wb, "sign_med_FL", sign_med_FL, headerStyle = 									header_style, borders = "all",rowNames = TRUE)


saveWorkbook(wb, "Mediation-PLS-SEM - Promise Aguda- Objective 2.xlsx", overwrite = TRUE)


message("✅ Export complete: PLS results written to Mediation-PLS-SEM - Promise Aguda- Objective 2.xlsx")



### Bootstrapping the results
boot_pls_med <- bootstrap_model(seminr_model = pl_sm_med,
                                nboot = 1000,
                                cores = NULL,
                                seed = 123)

## Summarize the results of the bootstrap
sum_boot_pls_med <- summary(boot_pls_med, alpha = 0.05) 


# Get the direct effect significance of the mediating variable 
se_sig_med_FL <- specific_effect_significance(boot_pls_med, 
                                              from = "MAT",
                                              through = "FL",
                                              to = "OP",
                                              alpha = 0.05) 


### Print the result

se_sig_med_FL

# Check the rownames 
rownames(se_sig_med_FL)

# Convert bootstrap results to data.frame 
#se_sig_med_FL <- as.data.frame(se_sig_med_FL)
se_sig_med_FL # Print to see the content



# Compute p-values (using "T Stat." column with dot)
se_sig_med_FL$p_value <- round(2 * (1 - pnorm(abs(se_sig_med_FL[,"T Stat."]))),4)

colnames(se_sig_med_FL)
head(se_sig_med_FL)

# Add significance levels
se_sig_med_FL$Significance <- cut(
  se_sig_med_FL$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
se_sig_med_FL <- se_sig_med_FL[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                   "2.5% CI","97.5% CI", "p_value" ,      
                                   "Significance" )]

# Rename columns for clarity
colnames(se_sig_med_FL) <-  c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                              "2.5% CI","97.5% CI", "p_value" ,      
                              "Significance" )




#### Obtain results on model estimates bootstrap such as the path coefficients with sum_boot_pls_med$bootstrapped_paths.

######## Get the P-value and save the bootstrapping result to csv #################################

sum_boot_paths_med <- sum_boot_pls_med$bootstrapped_paths

### Check the class of  sum_boot_paths_med

class(sum_boot_paths_med)


# Check the rownames 
rownames(sum_boot_paths_med)

# Convert bootstrap results to data.frame 
sum_boot_paths_med <- as.data.frame(sum_boot_pls_med$bootstrapped_paths)
sum_boot_paths_med # Print to see the content


# Compute p-values (using "T Stat." column with dot)
sum_boot_paths_med$p_value <- round(2 * (1 - pnorm(abs(sum_boot_paths_med[,"T Stat."]))),4)

colnames(sum_boot_paths_med)
head(sum_boot_paths_med)

# Add significance levels
sum_boot_paths_med$Significance <- cut(
  sum_boot_paths_med$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_paths_med <- sum_boot_paths_med[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                  "2.5% CI","97.5% CI", "p_value" ,      
                                                  "Significance" )]

# Rename columns for clarity
colnames(clean_results_paths_med) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                        "2.5% CI","97.5% CI", "P-value" ,      
                                        "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_paths_med,
  file = "path_bootstrap_results_med- Promise Aguda- Objective 2.csv",
  row.names = TRUE)


# Confirm location
cat("✅ Clean results with CIs saved as 'path_bootstrap_results_med- Promise Aguda- Objective 2.csv' in your working directory\n")


#### Bootstrapping of outer loadings 
####### Get the P-value and save the bootstrapping result to csv #################################


sum_boot_loadings_med  <- sum_boot_pls_med$bootstrapped_loadings

### Check the class of  sum_boot_loadings

class(sum_boot_loadings_med)

# Check the rownames 
rownames(sum_boot_loadings_med)

# Convert bootstrap results to data.frame 

sum_boot_loadings_med <- as.data.frame(sum_boot_pls_med$bootstrapped_loadings)
sum_boot_loadings_med # Print to see the contents


# Compute p-values (using "T Stat." column with dot)
sum_boot_loadings_med$p_value <- round(2 * (1 - pnorm(abs(sum_boot_loadings_med[,"T Stat."]))),4)

### Get the column headers
colnames(sum_boot_loadings_med)
head(sum_boot_loadings_med)

# Add significance levels
sum_boot_loadings_med$Significance <- cut(
  sum_boot_loadings_med$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_loadings_med <- sum_boot_loadings_med[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                        "2.5% CI","97.5% CI", "p_value" ,      
                                                        "Significance" )]

# Rename columns for clarity
colnames(clean_results_loadings_med) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                           "2.5% CI","97.5% CI", "P-value" ,      
                                           "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_loadings_mod,
  file = "loadings_boostrap_med- Promise Aguda- Objective 2.csv",
  row.names = TRUE
)



# Confirm location
cat("✅ Clean results of loadings with CIs saved as 'outer_loadings_boostrap_med- Promise Aguda- Objective 2.csv' in your working directory\n")




### Bootstrapping the model fit result

boot_mf_med <-
  
  cSEM(.data = dt, .model = cSEM_model_med,
       .resample_method = "bootstrap", .R = 1000)

boot_mf_results_med <- assess(boot_mf_med)


boot_mf_results_med 


# Saving the bootstrapping results to file


## Summarize the PLS-SEM Bootstrapping  outputs including specific direct effect and take them to a single Excel file


####################### FORMATTED VERSION ##########################################################################


# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file




# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file

# Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)

wb <- createWorkbook()

# --- Bootstrap results ---


wb <- createWorkbook()
addWorksheet(wb, "sum_boot_paths_med"); writeData(wb, "sum_boot_paths_med", clean_results_paths_med, headerStyle = header_style, 
                                                  borders = "all",rowNames = TRUE)

addWorksheet(wb, "sum_boot_loadings_med"); writeData(wb, "sum_boot_loadings_med", clean_results_loadings_med, headerStyle = header_style, 
                                                     borders = "all",rowNames = TRUE)


addWorksheet(wb, "se_sig_med_FL"); writeData(wb, "se_sig_med_FL", se_sig_med_FL, headerStyle = header_style, 
                                             borders = "all",rowNames = TRUE)

saveWorkbook(wb, "Promise Aguda PLS_SEM_with_BootstrapMed- Objective 2.xlsx ", overwrite = TRUE)

message("✅ Export complete: Bootstrap results written to Promise Aguda PLS_SEM_with_BootstrapMed- Objective 2.xlsx")


# Create the Visualization

plot(pl_sm_med,
     what = "paths",
     engine = "DiagrammeR",
     title = " ",
     node_labels = TRUE,
     node_color = "lightgreen",
     node_shape = "ellipse",
     fontname = "Arial",
     fontsize = 12,
     edge_labels = TRUE,
     edge_label_color = "black",
     edge_color = "darkblue",
     edge_width = 2,
     layout = "tree")
dev.off()

# To save plot
save_plot("Promise Aguda Objective 2 - Mediation image.png")

# Save high-quality PNG
save_plot(filename = "Promise Aguda Objective 2 - Mediation image.png",
          width = 10, height = 7) # dpi = 600





###################### Mediation Analysis - Objective 3######################################################################################


## Create the measurement model

mm_med <- constructs(
  composite("MAT", multi_items("MAT", 1:3), weights = mode_A),
  composite("ITR",  multi_items("ITR", 1:4), weights = mode_A),
  composite("OP",  multi_items("OP", 1:3), weights = mode_A)
  #composite("MAT",  multi_items("MAT", 1:3), weights = mode_B),  # Formative model
)  


## Create the structural model
sm_med <- relationships(
  paths(from = "MAT", to = "ITR"),
  paths(from = "MAT", to = "MAT"),
  paths(from = "ITR", to = "OP")  # mediating effect
) 

## Create the structural model - Method 2
# Structural model with mediation
sm_med <- relationships(
  paths(from = "MAT", to = c("ITR", "OP")),  # MAT affects ITR and OP
  paths(from = "ITR", to = "OP")             # ITR mediates OP
)


# Next, we estimate the model with estimate_pls(), store it to pl_sm_med and summarize it to sum_pls_med. Further, we also apply bootstrapping and summarize the bootstrapped model with an alpha level of 5% (summary(boot_corp_rep_med, alpha = 0.05))`

## Estimate the new model with mediator
pl_sm_med <- estimate_pls(
  data = dt,
  measurement_model = mm_med,
  structural_model = sm_med,
  # missing = mean_replacement,
  missing_value = "-99"
)

## Extract the summary
sum_pls_med <- summary(pl_sm_med)

### Inspect the total effects
sum_pls_med$total_effects

### Inspect the total indirect effects
sum_pls_med$total_indirect_effects


#### calling summary_pls_model$paths, we inspect the model's path coefficients and the (adjusted) R2 values 
sum_pls_med$paths

#### calling summary_pls_model$reliability, we inspect the construct reliability metrics
sum_pls_med$reliability


#### we can plot the reliability
plot(sum_pls_med$reliability)



#### calling summary_pls_model$validity, we inspect the construct validity metrics # Check this out first to see contents

sum_pls_med$validity


#### calling summary_pls_model$validity$ITR_criteria, we obtain Discriminant validty, specifically, Fornell-Larcker criterion (Fornell &  Larcker, 1981)

sum_pls_med$validity$ITR_criteria

#### Calling summary_pls_model$validity$htmt, we inspect heterotrait-monotrait ratio (HTMT)
sum_pls_med$validity$htmt


### Calling summary_pls_model$validity$vif_item, we inspect the VIF for collinearity

sum_pls_med$validity$vif_items



# Mediation collinearity fix - Make it be in data frame
## A mediator might not have item-level VIFs. So, NA is reported
# Convert VIF list into a tidy data frame, including empty constructs

collinearity_med_df <- do.call(rbind, lapply(names(sum_pls_med$validity$vif_items), function(construct) {
  vif_vals <- sum_pls_med$validity$vif_items[[construct]]
  
  if (length(vif_vals) == 0) {
    # If construct has no VIF items, add a placeholder
    data.frame(
      Construct = construct,
      Item      = NA,
      VIF       = NA
    )
  } else {
    data.frame(
      Construct = construct,
      Item      = names(vif_vals),
      VIF       = unname(vif_vals)
    )
  }
}))




#### We can access summary statistics such as mean, standard deviation and number of missing values for the model’s items

sum_pls_med$descriptives$statistics$items


##. Construct scores (latent variable scores)

construct_scores_med <- sum_pls_med$composite_scores 
construct_scores_med

# Alternative to the above
#construct_scores_med <- sum_pls_med$construct_scores
#construct_scores_med


##. Outer loadings (indicator reliability)
sum_pls_med$loadings

## Or
outer_loadings_pl_sm_med <- pl_sm_med$outer_loadings
print(outer_loadings_pl_sm_med)


##. weights
pl_sm_med$outer_weights

# Or
outer_weights_pl_sm_med <- sum_pls_med$weights
print(outer_weights_pl_sm_med)

# Compute cross-loadings manually
cross_loadings_pl_sm_med <- sum_pls_med$validity$cross_loadings


# To get the effect size
fsquare_pls_med  <- sum_pls_med$fSquare


### Calculate the sign of p1*p2*p3, i.e., sign of interaction

sign_med_ITR <- sum_pls_med$paths["MAT","OP"]*sum_pls_med$paths["MAT","ITR"]*sum_pls_med$paths["ITR","OP"] # if positive, ITR is a complementary partial mediator in # the relationship between MAT and OP
sign_med_ITR
# if negative, ITR is a competitive partial mediator in the relationship between  MAT and OP

### Try out - Check the components of the sign of interaction

sum_pls_med$paths["MAT","OP"]
sum_pls_med$paths["MAT","ITR"]
sum_pls_med$paths["ITR","OP"]




### Get model fit using the cSEM package

cSEM_model_med <- "

# measurement model
MAT =~ MAT1 + MAT2 + MAT3
OP =~ OP1 + OP2 + OP3
ITR =~ ITR1 + ITR2 + ITR3 + ITR4 + ITR5

# Structural model 

OP ~ MAT + ITR 

"
mf_med <- 
  cSEM(.data = dt, .model = cSEM_model_med)

mf_results_med <- assess <- assess(.object = mf_med, .quality_criterion =
                                     c("srmr", "dg","dl","chi_square"))

mf_results_med 

# Saving the PL-SEM results to file


####################### FORMATTED VERSION ##########################################################################


## Summarize the PLS-SEM model outputs and take them to a single Excel file

### Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)


wb <- createWorkbook()
addWorksheet(wb, "total_effects_med"); writeData(wb, "total_effects_med", sum_pls_med$total_effects, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "total_indirect_effects_med"); writeData(wb, "total_indirect_effects_med", sum_pls_med$total_indirect_effects, headerStyle = 										header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Paths_med");        writeData(wb, "Paths_med", sum_pls_med$paths, headerStyle = header_style, borders = "all",rowNames = 				TRUE)
addWorksheet(wb, "Loadings_med");     writeData(wb, "Loadings_med", sum_pls_med$loadings,, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "cross_loadings_med");     writeData(wb, "cross_loadings_med", sum_pls_med$validity$cross_loadings, headerStyle 																	= 															header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "Weights_med");      writeData(wb, "Weights_med", sum_pls_med$weights, headerStyle = header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "Reliability_med");  writeData(wb, "Reliability_med", sum_pls_med$reliability, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "HTMT_med");         writeData(wb, "HTMT_med", sum_pls_med$validity$vif_items, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "fSquare_med");      writeData(wb, "fSquare_med", sum_pls_med$fSquare, headerStyle = header_style, borders = "all",rowNames = TRUE)
addWorksheet(wb, "collinearity_med_df");  writeData(wb, "collinearity_med_df", collinearity_med_df, headerStyle = header_style, borders = 										"all",rowNames = TRUE)
addWorksheet(wb, "fornell_larcker_med"); writeData(wb, "fornell_larcker_med", sum_pls_med$validity$ITR_criteria, headerStyle = header_style, 										borders = "all",rowNames = TRUE)

addWorksheet(wb, "items_statistics_med"); writeData(wb, "items_statistics_med", sum_pls_med$descriptives$statistics$items, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "construct_scores_med"); writeData(wb, "construct_scores_med",sum_pls_med$composite_scores, headerStyle = 									header_style, borders = "all",rowNames = TRUE)

addWorksheet(wb, "sign_med_ITR"); writeData(wb, "sign_med_ITR", sign_med_ITR, headerStyle = 									header_style, borders = "all",rowNames = TRUE)


saveWorkbook(wb, "Mediation-PLS-SEM - Promise Aguda- Objective 3.xlsx", overwrite = TRUE)


message("✅ Export complete: PLS results written to Mediation-PLS-SEM - Promise Aguda- Objective 3.xlsx")



### Bootstrapping the results
boot_pls_med <- bootstrap_model(seminr_model = pl_sm_med,
                                nboot = 1000,
                                cores = NULL,
                                seed = 123)

## Summarize the results of the bootstrap
sum_boot_pls_med <- summary(boot_pls_med, alpha = 0.05) 


# Get the direct effect significance of the mediating variable 
se_sig_med_ITR <- specific_effect_significance(boot_pls_med, 
                                               from = "MAT",
                                               through = "ITR",
                                               to = "OP",
                                               alpha = 0.05) 


### Print the result

se_sig_med_ITR

# Check the rownames 
rownames(se_sig_med_ITR)

# Convert bootstrap results to data.frame 
#se_sig_med_ITR <- as.data.frame(se_sig_med_ITR)
se_sig_med_ITR # Print to see the content



# Compute p-values (using "T Stat." column with dot)
se_sig_med_ITR$p_value <- round(2 * (1 - pnorm(abs(se_sig_med_ITR[,"T Stat."]))),4)

colnames(se_sig_med_ITR)
head(se_sig_med_ITR)

# Add significance levels
se_sig_med_ITR$Significance <- cut(
  se_sig_med_ITR$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
se_sig_med_ITR <- se_sig_med_ITR[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                     "2.5% CI","97.5% CI", "p_value" ,      
                                     "Significance" )]

# Rename columns for clarity
colnames(se_sig_med_ITR) <-  c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                               "2.5% CI","97.5% CI", "p_value" ,      
                               "Significance" )




#### Obtain results on model estimates bootstrap such as the path coefficients with sum_boot_pls_med$bootstrapped_paths.

######## Get the P-value and save the bootstrapping result to csv #################################

sum_boot_paths_med <- sum_boot_pls_med$bootstrapped_paths

### Check the class of  sum_boot_paths_med

class(sum_boot_paths_med)


# Check the rownames 
rownames(sum_boot_paths_med)

# Convert bootstrap results to data.frame 
sum_boot_paths_med <- as.data.frame(sum_boot_pls_med$bootstrapped_paths)
sum_boot_paths_med # Print to see the content


# Compute p-values (using "T Stat." column with dot)
sum_boot_paths_med$p_value <- round(2 * (1 - pnorm(abs(sum_boot_paths_med[,"T Stat."]))),4)

colnames(sum_boot_paths_med)
head(sum_boot_paths_med)

# Add significance levels
sum_boot_paths_med$Significance <- cut(
  sum_boot_paths_med$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_paths_med <- sum_boot_paths_med[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                  "2.5% CI","97.5% CI", "p_value" ,      
                                                  "Significance" )]

# Rename columns for clarity
colnames(clean_results_paths_med) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                        "2.5% CI","97.5% CI", "P-value" ,      
                                        "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_paths_med,
  file = "path_bootstrap_results_med- Promise Aguda- Objective 3.csv",
  row.names = TRUE)


# Confirm location
cat("✅ Clean results with CIs saved as 'path_bootstrap_results_med- Promise Aguda- Objective 3.csv' in your working directory\n")


#### Bootstrapping of outer loadings 
####### Get the P-value and save the bootstrapping result to csv #################################


sum_boot_loadings_med  <- sum_boot_pls_med$bootstrapped_loadings

### Check the class of  sum_boot_loadings

class(sum_boot_loadings_med)

# Check the rownames 
rownames(sum_boot_loadings_med)

# Convert bootstrap results to data.frame 

sum_boot_loadings_med <- as.data.frame(sum_boot_pls_med$bootstrapped_loadings)
sum_boot_loadings_med # Print to see the contents


# Compute p-values (using "T Stat." column with dot)
sum_boot_loadings_med$p_value <- round(2 * (1 - pnorm(abs(sum_boot_loadings_med[,"T Stat."]))),4)

### Get the column headers
colnames(sum_boot_loadings_med)
head(sum_boot_loadings_med)

# Add significance levels
sum_boot_loadings_med$Significance <- cut(
  sum_boot_loadings_med$p_value,
  breaks = c(-Inf, 0.001, 0.01, 0.05, Inf),
  labels = c("p < 0.001", "p < 0.01", "p < 0.05", "ns")
)

# Create a clean table with selected columns
clean_results_loadings_med <- sum_boot_loadings_med[, c("Original Est.",  "Bootstrap Mean", "Bootstrap SD",  "T Stat.",
                                                        "2.5% CI","97.5% CI", "p_value" ,      
                                                        "Significance" )]

# Rename columns for clarity
colnames(clean_results_loadings_med) <-  c("Original Estimate",  "Bootstrap Mean", "Bootstrap SD",  "T Statistic",
                                           "2.5% CI","97.5% CI", "P-value" ,      
                                           "Significance" )


# Export to CSV (saves in working directory)
write.csv(
  clean_results_loadings_mod,
  file = "loadings_boostrap_med- Promise Aguda- Objective 3.csv",
  row.names = TRUE
)



# Confirm location
cat("✅ Clean results of loadings with CIs saved as 'outer_loadings_boostrap_med- Promise Aguda- Objective 3.csv' in your working directory\n")




### Bootstrapping the model fit result

boot_mf_med <-
  
  cSEM(.data = dt, .model = cSEM_model_med,
       .resample_method = "bootstrap", .R = 1000)

boot_mf_results_med <- assess(boot_mf_med)


boot_mf_results_med 


# Saving the bootstrapping results to file


## Summarize the PLS-SEM Bootstrapping  outputs including specific direct effect and take them to a single Excel file


####################### FORMATTED VERSION ##########################################################################


# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file




# Summarize the PLS-SEM bootstrapping outputs and take them to a single Excel file

# Define a reusable header style
header_style <- createStyle(
  fontSize   = 12,
  fontColour = "black",
  halign     = "center",
  fgFill     = "#4FBD81",
  border     = "Bottom"
)

wb <- createWorkbook()

# --- Bootstrap results ---


wb <- createWorkbook()
addWorksheet(wb, "sum_boot_paths_med"); writeData(wb, "sum_boot_paths_med", clean_results_paths_med, headerStyle = header_style, 
                                                  borders = "all",rowNames = TRUE)

addWorksheet(wb, "sum_boot_loadings_med"); writeData(wb, "sum_boot_loadings_med", clean_results_loadings_med, headerStyle = header_style, 
                                                     borders = "all",rowNames = TRUE)


addWorksheet(wb, "se_sig_med_ITR"); writeData(wb, "se_sig_med_ITR", se_sig_med_ITR, headerStyle = header_style, 
                                              borders = "all",rowNames = TRUE)

saveWorkbook(wb, "Promise Aguda PLS_SEM_with_BootstrapMed- Objective 3.xlsx ", overwrite = TRUE)

message("✅ Export complete: Bootstrap results written to Promise Aguda PLS_SEM_with_BootstrapMed- Objective 3.xlsx")


# Create the Visualization

plot(pl_sm_med,
     what = "paths",
     engine = "DiagrammeR",
     title = " ",
     node_labels = TRUE,
     node_color = "lightgreen",
     node_shape = "ellipse",
     fontname = "Arial",
     fontsize = 12,
     edge_labels = TRUE,
     edge_label_color = "black",
     edge_color = "darkblue",
     edge_width = 2,
     layout = "tree")
dev.off()

# To save plot
save_plot("Promise Aguda Objective 3 - Mediation image.png")

# Save high-quality PNG
save_plot(filename = "Promise Aguda Objective 3 - Mediation image.png",
          width = 10, height = 7) # dpi = 600



